### ISSUE TITLE
Store the login-domains for a tenant

### ISSUE THREAD

**Issue by ulrichSchreiner** [metal-stack/masterdata-api#11]
We want to do a 2FA for our tenants. When a user logs in with his/her email address, we have to find out to which tenant a user belongs.

It seems useful to add a field `Domains []string` to the tenant so we can detect the tenant from the login. We should not use a single domain as some of our customers have subsidiary companies with different domains.

It would also be great to have a RPC call to get the tenant from a given domain.

**Comment by majst01** [comment]
as we have arbitrary annotations and labels on a tenant, isnt that sufficient to store such data ?
Also fetching all tenants and then check for valid domains seems fast enough as we dont expect to have thousands of tenants. Albeit a listTenant endpoint is not yet implemented in cloud-api.

**Comment by ulrichSchreiner** [comment]
@droid42 and i discussed it: the user has to login with `<userid>@<tenantid>` and not with the email adress. so i close this issue.
