### ISSUE TITLE
Implement fields for sending auditlogs to splunk

### ISSUE THREAD

**Issue by mreiger** [metal-stack/masterdata-api#23]
Create fields in the masterdata api to send auditlog events to splunk.

Proposed structure:

* tenant master-data
  * name/desc
* tenant settings
  * cloud
    * limit max projects
    * limit max clusters
  * cluster
    * limit
  * **splunk**
    * **HEC endpoint**
    * **HEC token**
    * **Client certificate to authenticate to HEC endpoint**
    * **Private key corresponding to client certificate**
* tenant project
  * settings
    * limit max clusters

**Question:**

Should we include a switch to skip certificate verification?

Complements https://github.com/metal-stack/gardener-extension-provider-metal/issues/54

**Comment by Gerrit91** [comment]
In my opinion the certificates should also be included in there. When the API can tell you where to connect to it should also know how a client can to connect. I also do not know where else we could reasonably store this information.

**Comment by majst01** [comment]
But these information must be stored in annotations, no modifications to masterdata-api required.
